# Generated by Django 4.0.3 on 2022-04-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieInfoApp', '0004_alter_movie_releasedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
    ]
