# Generated by Django 4.0.3 on 2022-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieInfoApp', '0005_rename_name_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
